app:
  name: api-tester
  env: prod

source:
  project_root: /workspace/target-project
  router_dirs:
    - src/routers
  exclude_paths:
    - __pycache__
    - __MACOSX
  endpoint_yaml_path: configs/endpoints.generated.yaml

api:
  base_url: https://216.176.194.30:8089
  apikey: 9RObPxOBC4Sq6YOMu95mEEWPoIaDE4rm
  apikey_header: Apikey
  headers:
    Accept: application/json
  task_status_path: /api/public/task
  task_status_method: GET
  task_status_id_field: task_id
  task_status_value_key: status
  success_statuses: [2]
  failure_statuses: [-1]
  request_timeout_sec: 30
  insecure_skip_verify: false
  request_encoding: form

runner:
  mode: smoke
  scan_on_startup: false
  concurrency: 8
  poll_interval_sec: 3
  task_timeout_sec: 900
  http_timeout_sec: 30
  max_endpoint_rounds: 1
  retry_count: 1
  retry_backoff_ms: 1500
  report_dir: reports
  only_include_task_apis: false

stress:
  enabled: false
  concurrency: 20
  duration_sec: 0
  per_endpoint_rounds: 2
  global_rate_limit_rps: 10
  stop_on_high_failure_rate: true
  high_failure_rate_pct: 40

schedule:
  enabled: true
  cron: "0 3 * * *"
  run_at_start: false

database:
  path: data/api_tester.db

web:
  listen_addr: ":18081"
  base_path: /

overrides:
  defaults:
    bid: 898b0d60-da10-44e0-a7eb-46b3455878e5
    fee: "10"
    title: 12312323123
  by_parameter_name:
    first_image:
      - https://imgpublic.ycomesc.live/upload_01/upload/20250902/2025090214525538512.jpeg
    end_image:
      - https://pic.rmb.bdstatic.com/bjh/250622/beautify/20019de7ad4a6bae7da522da5c3f1555.jpeg?for=bg
    source_path:
      - https://imgpublic.ycomesc.live/upload_01/upload/20250902/2025090214525538512.jpeg
    image:
      - https://imgpublic.ycomesc.live/upload_01/upload/20250902/2025090214525538512.jpeg
    scene_name:
      - default_scene
    output_format:
      - png
      - video
    notify_url:
      - https://quiet-whale-88.webhook.cool
  by_path:
    /api/public/generate/kiss/video:
      first_image:
        - https://imgpublic.ycomesc.live/upload_01/upload/20250902/2025090214525538512.jpeg
      end_image:
        - https://pic.rmb.bdstatic.com/bjh/250622/beautify/20019de7ad4a6bae7da522da5c3f1555.jpeg?for=bg
      bid:
        - 898b0d60-da10-44e0-a7eb-46b3455878e5
      fee:
        - "10"
      title:
        - 12312323123
    /api/public/task:
      task_id:
        - 167d3c28-ca32-4df8-b454-53cfe0e332c2
  disabled_paths:
    - /api/mq/queues/action
